version: '3'
services: 
    postgress:
#       image: 'postgres:9.6.17-alpine'   # there is no specific alpine version
        image: 'postgres:12.2-alpine'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
#       image: 'redis:5.0.8-alpine3.11'   # this is the latest right now
        image: 'redis:5.0-alpine'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    fib-server-api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
#            local dir:image dir
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    fib-client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    fib-worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
